
#screen dimensions
SCREEN_HEIGHT = 464
SCREEN_WIDTH = 1000
SCREEN_SIZE = (SCREEN_HEIGHT,SCREEN_WIDTH)

#colours (red, green,  blue)
BLACK = (0,0,0)
RED = (255,0,0)

#tps
TPS_MAX = 70.0

#level size
LEVEL_WIDTH = 6784
LEVEL_HEIGHT = SCREEN_HEIGHT
WIDTH_ELEMENTS = 212
HEIGHT_ELEMENTS = 14
MULTIPLICATION = 32

#mario size
MARIO_HEIGHT = 64
MARIO_WIDTH = 32